pub mod acp;
#[cfg(feature = "tauri-runtime")]
pub mod app_update;
pub mod automation;
pub mod background;
pub mod backup;
pub mod cerebro;
pub mod chat_authoring;
pub mod chat_channel;
pub mod conversations;
pub mod custom_agents;
pub mod custom_skills;
pub mod delegation;
pub mod experts;
pub mod feedback;
#[cfg(feature = "tauri-runtime")]
pub mod file_io;
pub mod folder_commands;
pub mod folder_links;
pub mod folders;
pub mod forge;
pub mod logging;
pub mod mcp;
pub mod model_provider;
pub mod office_tools;
pub mod open_in;
#[cfg(feature = "tauri-runtime")]
pub mod notification;
pub mod pet;
pub mod project_boot;
pub mod question;
pub mod quick_messages;
#[cfg(feature = "tauri-runtime")]
pub mod remote_proxy;
#[cfg(feature = "tauri-runtime")]
pub mod remote_workspace;
pub mod science;
pub mod session_info;
pub mod system_settings;
pub mod terminal;
pub mod token_usage;
pub mod turn_window;
pub mod version_control;
#[cfg(feature = "tauri-runtime")]
pub mod windows;
pub mod work_task;
pub mod workspace_state;
